<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace />
        <Title>$(AssemblyName)</Title>
        <Product>$(AssemblyName)</Product>
        <Version>7.0.1</Version>
        <Description>The library that allows you to easily implement a hierarchical object.</Description>
        <Authors>Denis535</Authors>
        <Company>Denis535</Company>
        <Copyright></Copyright>
        <RepositoryUrl>https://github.com/Denis535/DotNet-Libraries/tree/main/TreeMachine.Pro</RepositoryUrl>

        <IsPackable>true</IsPackable>
        <IsTool>false</IsTool>
        <DevelopmentDependency>false</DevelopmentDependency>

        <PackageId>$(AssemblyName)</PackageId>
        <PackageVersion>$(Version)</PackageVersion>
        <PackageDescription>$(Description)</PackageDescription>
        <PackageTags>tree-machine tree hierarchy hierarchical node pattern design-pattern</PackageTags>
        <PackageProjectUrl>https://github.com/Denis535/DotNet-Libraries/tree/main/TreeMachine.Pro</PackageProjectUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <RequireLicenseAcceptance>false</RequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>Icon.png</PackageIcon>

        <PackRelease>true</PackRelease>

        <EnableDefaultItems>true</EnableDefaultItems>
        <EnableDefaultNoneItems>true</EnableDefaultNoneItems>
        <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
        <EnableDefaultEmbeddedResourceItems>true</EnableDefaultEmbeddedResourceItems>

        <IncludeBuildOutput>true</IncludeBuildOutput>
        <IncludeContentInPack>true</IncludeContentInPack>
        <IncludeSymbols>true</IncludeSymbols>
        <IncludeSource>true</IncludeSource>

        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeBuilds</TargetsForTfmSpecificBuildOutput>
        <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeContent</TargetsForTfmSpecificContentInPackage>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="TreeMachine.Pro.Extensions" />
        <InternalsVisibleTo Include="TreeMachine.Pro.Tests" />
    </ItemGroup>

    <ItemGroup>
        <Clean Include="$(PackageOutputPath)\*.nupkg" />
    </ItemGroup>

    <Target Name="IncludeBuilds">
        <ItemGroup>
            <BuildOutputInPackage Include="..\$(AssemblyName).Extensions\bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).Extensions.dll" />
        </ItemGroup>
    </Target>

    <Target Name="IncludeContent">
        <ItemGroup>
            <TfmSpecificPackageFile Include="../LICENSE" PackagePath="/" />
            <TfmSpecificPackageFile Include="../README.md" PackagePath="/" />
            <TfmSpecificPackageFile Include="../Icon.png" PackagePath="/" />
        </ItemGroup>
    </Target>

</Project>
