<Project>

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace />
        <Title>$(AssemblyName)</Title>
        <Product>$(AssemblyName)</Product>
        <Version>1.13.5</Version>
        <Description>The framework that guides you to design a high-quality architecture for your game project.</Description>
        <Authors>Denis535</Authors>
        <Company>Denis535</Company>
        <RepositoryUrl>https://github.com/Denis535/DotNet-Libraries/tree/main/GameFramework.Pro</RepositoryUrl>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

</Project>