<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <IsTool>false</IsTool>
        <DevelopmentDependency>false</DevelopmentDependency>

        <PackageId>$(AssemblyName)</PackageId>
        <PackageVersion>$(Version)</PackageVersion>
        <PackageDescription>$(Description)</PackageDescription>
        <PackageTags>gamedev architecture framework game-architecture game-framework pattern design-pattern best-practices</PackageTags>
        <PackageProjectUrl>https://github.com/Denis535/DotNet.Libraries/tree/main/GameFramework.Pro</PackageProjectUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageLicenseUrl></PackageLicenseUrl>
        <RequireLicenseAcceptance>false</RequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>Icon.png</PackageIcon>
        <PackageIconUrl></PackageIconUrl>

        <PackRelease>true</PackRelease>

        <EnableDefaultItems>true</EnableDefaultItems>
        <EnableDefaultNoneItems>true</EnableDefaultNoneItems>
        <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
        <EnableDefaultEmbeddedResourceItems>true</EnableDefaultEmbeddedResourceItems>

        <IncludeBuildOutput>true</IncludeBuildOutput>
        <IncludeContentInPack>true</IncludeContentInPack>
        <IncludeSymbols>true</IncludeSymbols>
        <IncludeSource>true</IncludeSource>

        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeBuilds</TargetsForTfmSpecificBuildOutput>
        <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeContent</TargetsForTfmSpecificContentInPackage>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameFramework.Pro.Internal\GameFramework.Pro.Internal.csproj">
            <PrivateAssets>all</PrivateAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="StateMachine.Pro" Version="7.0.2" />
        <PackageReference Include="TreeMachine.Pro" Version="7.0.2" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="GameFramework.Pro.Extensions" />
        <InternalsVisibleTo Include="GameFramework.Pro.Tests" />
    </ItemGroup>

    <ItemGroup>
        <Clean Include="$(PackageOutputPath)\*.nupkg" />
    </ItemGroup>

    <Target Name="IncludeBuilds">
        <ItemGroup>
            <BuildOutputInPackage Include="..\GameFramework.Pro.Internal\bin\$(Configuration)\$(TargetFramework)\GameFramework.Pro.Internal.dll" />
            <BuildOutputInPackage Include="..\GameFramework.Pro.Extensions\bin\$(Configuration)\$(TargetFramework)\GameFramework.Pro.Extensions.dll" />
        </ItemGroup>
    </Target>

    <Target Name="IncludeContent">
        <ItemGroup>
            <TfmSpecificPackageFile Include="../LICENSE" PackagePath="/" />
            <TfmSpecificPackageFile Include="../README.md" PackagePath="/" />
            <TfmSpecificPackageFile Include="../Icon.png" PackagePath="/" />
        </ItemGroup>
    </Target>

</Project>
